routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/login', function () {
    return view('login');
});
Route::post('/login', 'LoginController@login')->name('login');
Route::get('/user-info/{data}', 'UserController@userInfo')->name('user.info');

Route::group(['middleware'=>'auth:web'],function (){
    Route::get('/dashboard','DashbarodController@index')->name('dashboard');
    Route::get('/profile','UserController@profile')->name('profile');
    Route::post('/profile','UserController@profileUpdate')->name('profile.update');
    Route::get('/logout','LoginController@logout')->name('logout');
    // Designation Route
    Route::group(['prefix'=>'/designation'],function (){
        Route::get('/','DesignationController@index')->name('designation.index')->middleware('permission:designation_manage');
        Route::post('/store','DesignationController@store')->name('designation.store')->middleware('permission:designation_manage');
        Route::post('/{id}/update','DesignationController@update')->name('designation.update')->middleware('permission:designation_manage');
    });
    // Department Route
    Route::group(['prefix'=>'/department'],function (){
        Route::get('/','DepartmentController@index')->name('department.index')->middleware('permission:department_manage');
        Route::post('/store','DepartmentController@store')->name('department.store')->middleware('permission:department_manage');
        Route::post('/{id}/update','DepartmentController@update')->name('department.update')->middleware('permission:department_manage');
        Route::post('/get-designation','DepartmentController@designation')->name('department.designation')->middleware('permission:department_manage');
    });
    // Role Route
    Route::group(['prefix'=>'/role'],function (){
        Route::get('/','RoleController@index')->name('role.index')->middleware('permission:manage_role');
        Route::post('/store','RoleController@store')->name('role.store')->middleware('permission:manage_role');
        Route::post('/{id}/update','RoleController@update')->name('role.update')->middleware('permission:manage_role');
    });
    // Permission Route
    Route::group(['prefix'=>'/permission'],function (){
        Route::get('/','PermissionController@index')->name('permission.index')->middleware('permission:manage_permission');
        Route::post('/store','PermissionController@store')->name('permission.store')->middleware('permission:manage_permission');
        Route::post('/{id}/update','PermissionController@update')->name('permission.update')->middleware('permission:manage_permission');
    });
    // User Route
    Route::group(['prefix'=>'/user'],function (){
        Route::get('/','UserController@index')->name('user.index')->middleware('permission:manage_user');
        Route::post('/store','UserController@store')->name('user.store')->middleware('permission:add_user');
        Route::get('/{user}/update-complain-solver-status','UserController@complainSolverStatusToggle')->name('user.complainSolver.status.toggle')->middleware('permission:add_user');
        Route::post('/{id}/update','UserController@update')->name('user.update')->middleware('permission:add_user');
        Route::get('/add-bulk','UserController@addBulk')->name('user.bulk')->middleware('permission:add_bulk_user');
        Route::post('/store-bulk','UserController@storeBulk')->name('user.bulk.store')->middleware('permission:add_bulk_user');
        Route::get('/generate-qr/{user}', 'UserController@generateQr')->name('user.generate.qr')->middleware('permission:generate_qr');
    });
    // Room Route
    Route::group(['prefix'=>'/room'],function (){
        Route::get('/','RoomController@index')->name('room.index')->middleware('permission:room_list');
        Route::post('/store','RoomController@store')->name('room.store')->middleware('permission:add_room');
        Route::post('/{id}/update','RoomController@update')->name('room.update')->middleware('permission:add_room');
    });
    // Booking Room Route
    Route::group(['prefix'=>'/booking-room'],function (){
        Route::get('/','RoomBookingController@index')->name('booking-room.index')->middleware('permission:booked_room_list');
        Route::post('/store','RoomBookingController@store')->name('booking-room.store')->middleware('permission:book_room');
        Route::post('/{id}/update','RoomBookingController@update')->name('booking-room.update')->middleware('permission:book_room');
        Route::get('/{id}/delete','RoomBookingController@delete')->name('booking-room.delete')->middleware('permission:book_room');
        Route::post('/available-room','RoomBookingController@getAvailableRoom')->name('available.room');
    });
    Route::get('/read-all','NotificationController@readNotification')->name('read.all');
    Route::post('/notification-all','NotificationController@notification')->name('notification.all');
    Route::get('/notification/{notification}/detail','NotificationController@detail')->name('notification.detail');
    // Transport Routes
    Route::group(['prefix'=>'/transport'],function (){
        Route::get('/','TranspotController@index')->name('transport.index')->middleware('permission:add_transport');
        Route::post('/store','TranspotController@store')->name('transport.store')->middleware('permission:add_transport');
        Route::post('/{id}/update','TranspotController@update')->name('transport.update')->middleware('permission:update_transport');
        Route::group(['prefix'=> '/trip'],function(){
            Route::get('/{transport}','TranspotController@tripList')->name('transport.trip.list');
            Route::post('/{transport}/{trip}/update','TranspotController@tripUpdate')->name('transport.trip.update');
        });
    });
    // Transport Request
    Route::group(['prefix'=>'/transport-request'],function (){
        Route::get('/','TranspotController@requestIndex')->name('transport.request.index')->middleware('permission:add_transport_request');
        Route::post('/store','TranspotController@requestStore')->name('transport.request.store')->middleware('permission:add_transport_request');
        Route::post('/{id}/delete','TranspotController@requestDelete')->name('transport.request.delete')->middleware('permission:update_transport_request');
        Route::get('/{id}/status-approve','TranspotController@requestApprove')->name('transport.request.status.approve')->middleware('permission:approve_reject_transport_request');
        Route::get('/approval/list','TranspotController@requestApprovalIndex')->name('transport.request.approval.index')->middleware('permission:approve_reject_transport_request');
        Route::get('/{id}/status-withdraw','TranspotController@requestStatusWithdraw')->name('transport.request.status.delete')->middleware('permission:update_transport_request');
        Route::post('/status-decline','TranspotController@requestReject')->name('transport.request.status.decline')->middleware('permission:approve_reject_transport_request');
        Route::post('/available-transport','TranspotController@getAvailableTransport')->name('available.transport');
        Route::post('/available-trip','TranspotController@getAvailableTrip')->name('available.trip');
    });
    // Sim management Route
    Route::group(['prefix'=>'/sim-management'],function (){

        Route::get('/','SimManagementController@index')->name('sim.index')->middleware('permission:sim_add_assign');
        Route::post('/store','SimManagementController@store')->name('sim.store')->middleware('permission:add_sim');
        Route::post('/{id}/update','SimManagementController@update')->name('sim.update')->middleware('permission:add_sim');
        Route::post('/assign','SimManagementController@assign')->name('sim.assign')->middleware('permission:sim_assign');
        Route::get('/{id}/unassign','SimManagementController@unAssign')->name('sim.unassign')->middleware('permission:sim_assign');
        Route::get('/report/{id}','SimManagementController@report')->name('sim.report')->middleware('permission:sim_manage');

        Route::get('/request-list','SimManagementController@requestList')->name('sim.request.list')->middleware('permission:sim_request_pending_list');
        Route::post('/request','SimManagementController@requestStore')->name('sim.request.store')->middleware('permission:add_sim_request');
        Route::post('/request/{id}/update','SimManagementController@requestupdate')->name('sim.request.update')->middleware('permission:add_sim_request');


        Route::get('/request','SimManagementController@request')->name('sim.request')->middleware('permission:sim_request_list');
        Route::get('/request/{id}/view','SimManagementController@requestView')->name('sim.request.view')->middleware('permission:add_sim_request');
        Route::get('/request-list/{id}/view','SimManagementController@requestActionView')->name('sim_rqeuest_action.view')->middleware('permission:sim_request_list');

        Route::post('/request-list/{id}/accept','SimManagementController@requestAccept')->name('sim.request.accept')->middleware('permission:sim_assign');
        Route::post('/request-list/{id}/decline','SimManagementController@requestDecline')->name('sim.request.decline')->middleware('permission:sim_assign');


    });

    // Complain management
    Route::group(['prefix'=>'/complain'],function (){
        Route::get('/','ComplainManagementController@index')->name('complain.index')->middleware('permission:register_complain');

app/ComplainComment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ComplainComment extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at'];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function getImageAttribute($value)
    {
        return $value ? asset('/').$value : null;
    }
}

resources/views/breadcrumb.blade.php
<div class="col-12">
    <div class="dashboard_header mb_10">
        <div class="row">
            <div class="col-lg-6">
                <div class="dashboard_header_title">
                    <h4>{{$title}}@if(isset($sub_title)) <small>({{$sub_title}})</small> @endif</h4>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="dashboard_breadcam text-right">
                    @if(!$title !== 'Dashboard') <p><a href="{{route('dashboard')}}">Dashboard</a> <i class="fas fa-caret-right"></i> {{$title}}</p> @endif
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/dashboard.blade.php
@extends('layout.master')
@section('style')
    <link href="{{asset('/')}}assets/fullcalender/packages/core/main.css" rel='stylesheet' />
    <link href="{{asset('/')}}assets/fullcalender/packages/daygrid/main.css" rel='stylesheet' />
@endsection
@push('css')
    <style>
        .fc-day-grid-event .fc-time {
            font-size: 18px !important;
        }
    </style>
@endpush

@section('content')
    <div class="main_content_iner">
        <div class="container-fluid p-0 sm_padding_15px">
            <div class="row">
                @include('breadcrumb', ['title' => 'Dashboard'])
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-4 mb-5">
                            <a href="{{route('room.index')}}"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Rooms', 'icon' => 'ti-home' , 'data' => $room])
                            </a>
                        </div>
                        <div class="col-md-4 mb-5">
                            <a href="{{route('sim.report', 1)}}"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Assigned SIM', 'icon' => 'ti-check-box' , 'data' => $total_sim->assigned ?? 0])
                            </a>
                        </div>
                        <div class="col-md-4 mb-5">
                            <a href="{{route('sim.report', 0)}}"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Un Assigned SIM', 'icon' => 'ti-na' , 'data' => $total_sim->un_assigned ?? 0])
                            </a>
                        </div>
                        <div class="col-md-4 mb-5">
                            <a href="{{route('booking-room.index')}}"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Last Week Meeting', 'icon' => 'ti-calendar' , 'data' => $past_total_meeting])
                            </a>
                        </div>
                        <div class="col-md-4 mb-5">
                            <a href="{{route('booking-room.index')}}"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Upcoming Meeting', 'icon' => 'ti-calendar' , 'data' => $coming_total_meeting])
                            </a>
                        </div>
                        <div class="col-md-4 mb-5">
                            {{--                            <a href="{{route('sim.request.list')}}"--}}
                            <a href="#"
                               class="metric metric-bordered align-items-center">
                                @include('common.customCard',['title' => 'Total Complain', 'icon' => 'ti-agenda' , 'data' => $total_complain_request])
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card_box box_shadow position-relative mb_30">
                        <!-- .card-body -->
                        <div class="white_box_tittle_custom bg-silken">
                            <h5 class="text-white">Meeting Leaderboard</h5>
                        </div>
                        <!-- .list-group -->
                        <div class="list-group list-group-flush">
                            <!-- .list-group-item -->
                            @foreach($user_meeting as $user)
                                <div class="list-group-item">
                                    <table>
                                        <tr class="text-center">
                                            <td>
                                                <div class="list-group-item-figure">
                                                    <a href="javascript:void(0)"
                                                       data-toggle="tooltip"
                                                       title=" {{$user->name}}">
                                                        <img src="{{asset('/uploads').'/'.$user->image}}" alt="" class="user-avatar">
                                                    </a>
                                                </div>
                                            </td>
                                            <td>
                                                {{$user->name}}
                                            </td>
                                            <td> :</td>
                                            <td>
                                                <strong>{{$user->total}}</strong>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- .list-group-item-figure -->
                                </div><!-- /.list-group-item -->
                            @endforeach
                            <!-- .list-group-item -->
                        </div><!-- /.list-group -->
                    </div><!-- /.card -->
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md-8">
                    <div class="c_card-card bg-silken">
                        <div class="c_card-title">Last 30 Days Meeting Man Hours</div>
                        <div class="d-flex justify-content-center align-items-center">
                            <canvas id='meeting-man-hour' height="132" style="background-color: #d0d0d0 !important; border-radius: 5px !important;"></canvas>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="c_card-card bg-silken">
                        <div class="c_card-title">Complain Status Ratio</div>
                        <div class="d-flex justify-content-center align-items-center">
                            <canvas id='complain-status-ratio' height="135" style="background-color: #d0d0d0 !important; border-radius: 5px !important;"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id='calendar'></div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src='{{asset('/')}}assets/fullcalender/packages/core/main.js'></script>
    <script src='{{asset('/')}}assets/fullcalender/packages/interaction/main.js'></script>
    <script src='{{asset('/')}}assets/fullcalender/packages/daygrid/main.js'></script>
@endsection
@push('script')
    {{--    <script src='{{asset('/')}}js/chart.min.js'></script>--}}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: [ 'interaction', 'dayGrid' ],
                header: {
                    left: 'prevYear,prev,next,nextYear today',
                    center: 'title',
                    right: 'dayGridMonth,dayGridWeek,dayGridDay'
                },
                defaultDate: "{{date('Y-m-d')}}",
                navLinks: false, // can click day/week names to navigate views
                editable: false,
                eventLimit: true, // allow "more" link when too many events
                events: @php echo $total_meeting; @endphp,
                eventTimeFormat: {
                    hour: 'numeric',
                    minute: '2-digit',
                    meridiem: true
                }
            });

            calendar.render();


            var lineChart = document.getElementById('meeting-man-hour').getContext('2d');

            new Chart(lineChart, {
                // The type of chart we want to create
                type: 'line',

                // The data for our dataset
                data: {
                    labels: [
                        @foreach ($meeting_man_hour as $manhour)
                            "{{$manhour->day}}",
                        @endforeach
                    ],
                    datasets: [{
                        label: "Man Hours",
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: [
                            @foreach ($meeting_man_hour as $manhour)
                                "{{$manhour->manhour}}",
                            @endforeach
                        ],
                    }]
                },

                // Configuration options go here
                options: {
                    responsive: true,
                    plugins: {
                        tooltip: {
                            callbacks: {
                                // Format tooltip value
                                label: (context) => {
                                    const label = context.dataset.label || '';
                                    const value = context.parsed.y || 0;
                                    return `${label}: ${value} h`; // Add "h" suffix
                                }
                            }
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: true,
                            ticks: {
                                // Optional: Add suffix to axis labels too
                                callback: (value) => `${value}h`
                            }
                        }
                    }
                }
            });


            //==================== PIE CHART ============================
            // Get the canvas context
            const pieChart = document.getElementById('complain-status-ratio').getContext('2d');
            let hoveredData = null;

            // Create gradients
            const createGradient = (color1, color2) => {
                const gradient = pieChart.createLinearGradient(0, 0, 400, 0);
                gradient.addColorStop(0, color1);
                gradient.addColorStop(1, color2);
                return gradient;
            };

            const gradients = [
                createGradient('#42d504', '#FFE66D'),
                createGradient('#4ECDC4', '#45B7D1'),
                createGradient('#f53f3f', '#FFEEAD')
            ];

            // Create the pie chart
            new Chart(pieChart, {
                type: 'pie',
                data: {
                    labels: [ @foreach ($complain_status_ratio->getAttributes() as $key => $data)
                        "{{ucfirst(str_replace('_', ' ', $key))}}",
                        @endforeach],
                    datasets: [{
                        label: 'Complain Count',
                        data: [@foreach ($complain_status_ratio->getAttributes() as $key => $data)
                            "{{$data}}",
                            @endforeach],
                        backgroundColor: gradients,
                        borderColor: '#fff', // Optional: Adds a white border around slices
                        borderWidth: 1
                    }]
                },
                options: {
                    cutout: '65%',
                    responsive: true,
                    plugins: {
                        legend: {
                            display: true,
                            position: 'bottom'
                        }
                    }
                }
            });
        });
    </script>
@endpush

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from uselooper.com/auth-signin-v2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 25 Sep 2019 14:10:02 GMT -->

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title> Hello Book || Login </title>
    <link rel="apple-touch-icon" sizes="144x144" href="{{asset('/')}}assets/images/logo-removebg-preview.png">
    <link rel="shortcut icon" href="{{asset('/')}}assets/images/logo-removebg-preview.png">
    <!-- Favicons -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet"><!-- End Google font -->
    <!-- BEGIN PLUGINS STYLES -->
    <link rel="stylesheet" href="{{asset('/')}}assets/vendor/fontawesome/css/all.css"><!-- END PLUGINS STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" href="{{asset('/')}}assets/stylesheets/theme.min.css" data-skin="default">
    <link rel="stylesheet" href="{{asset('/')}}css/custom.css">
</head>

<body>
<main class="container-fluid auth auth-floated">
    <div class="row">
        <div class="col-md-8">
            <div id="announcement" class="auth-announcement"
                 style="background-image:url('{{asset('/assets/images/Meeting Room Symbol.png')}}');background-repeat: no-repeat;background-position: center center;background-size: cover;">
                <img src="{{asset('/assets/images/unnamed.png')}}" alt="" class="login-img">
            </div>
        </div>
        <div class="col-md-4">
            <div class='auth-form'>
                <div class="mb-4">
                    <div class="mb-3 text-center">
                        <img class="rounded" src="{{asset('/')}}assets/images/logo-removebg-preview.png" alt="" height="72">
                    </div>
                </div>
                @include('status')
                    <form action="{{route('login')}}" method="POST">
                        {{csrf_field()}}
                        <div class="form-group mb-4">
                            <label class="d-block text-left" for="inputUser">Username</label>
                            <input type="text" id="inputUser" name="email" value="{{old('email')}}" class="form-control form-control-lg" required autofocus="" />
                        </div><!-- /.form-group -->
                        <!-- .form-group -->
                        <div class="form-group mb-4">
                            <label class="d-block text-left" for="inputPassword">Password</label>
                            <input type="password" id="inputPassword" name="password" value="{{old('password')}}" class="form-control form-control-lg" required>
                        </div><!-- /.form-group -->
                        <!-- .form-group -->
                        <div class="form-group mb-4">
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
                        </div><!-- /.form-group -->
                        <!-- copyright -->
                    </form><!-- /.auth-form -->
                    <p class="mb-0 px-3 text-muted text-center"> Silken Sewing © {{date('Y')}} All Rights Reserved.</p>
            </div>
        </div>
    </div>
</main><!-- /.auth -->
<!-- BEGIN BASE JS -->
<script src="assets/vendor/jquery/jquery.min.js"></script>
<script src="assets/vendor/bootstrap/js/popper.min.js"></script>
<script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script> <!-- END BASE JS -->
</body>
<!-- Mirrored from uselooper.com/auth-signin-v2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 25 Sep 2019 14:10:02 GMT -->

</html>

resources/views/profile.blade.php
@extends('layout.master')
@section('content')
    <div class="main_content_iner">
        <div class="container-fluid p-0 sm_padding_15px">
            <!-- metric row -->
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-body">
                                <div class="container center-div d-flex justify-content-center align-items-center">
                                    <img src="{{asset(auth()->user()->image ? '/uploads/'.auth()->user()->image :'uploads/image.png') }}" alt="Avatar"  class="profile-image img-thumbnail">
                                    <form action="{{route('profile.update')}}" method="post" enctype="multipart/form-data">
                                        {{csrf_field()}}
                                        <div class="profile-overlay">
                                            <label for="file-input">
                                                <i class="fa fa-image profile-icon"></i>
                                            </label>
                                            <input id="file-input" type="file" name="image" onchange="submit()"/>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card" style="padding-bottom: 38px">
                        <div class="card-body">
                            <div class="card-title d-flex justify-content-between align-items-center">
                                <h5>User Info</h5>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Name:</div>
                                <div class="col-6">{{auth()->user()->name}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Mobile No:</div>
                                <div class="col-6">{{auth()->user()->msisdn}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Email:</div>
                                <div class="col-6">{{auth()->user()->email}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">User Name:</div>
                                <div class="col-6">{{auth()->user()->username}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Employee ID:</div>
                                <div class="col-6">{{auth()->user()->employee_id}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Department:</div>
                                <div class="col-6">{{auth()->user()->getDepartment->name}}</div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6 text-muted">Designation:</div>
                                <div class="col-6">{{auth()->user()->getDesignation->name}}</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div><!-- /metric row -->
        </div><!-- /.section-block -->
    </div><!-- /.section-block -->
    <!-- grid row -->
@endsection
@push('script')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#imagePreview').css('background-image', 'url(' + e.target.result + ')');
                    $('#imagePreview').hide();
                    $('#imagePreview').fadeIn(650);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#imageUpload").change(function() {
            readURL(this);
        });
    </script>
@endpush